services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://127.0.0.1:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GIN_MODE=release
      - DATABASE_USER=postgres
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PASSWORD=database_password
      - DATABASE_PORT=5432
      - SERVER_PORT ="0.0.0.0:8000"
      - CORS_ALLOW_ORIGINS=http://127.0.0.1:5173,http://localhost:5173
    ports:
      - "8000:8000"

networks:
  mynetwork:
    driver: bridge

